-- Timed Kids production database, security policies and product-image storage.
-- Run the complete script once in the Supabase SQL Editor.

create extension if not exists "pgcrypto";

create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= price),
  stock integer not null default 0 check (stock >= 0),
  image_url text not null,
  video_url text,
  badge text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_orders (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'processing', 'delivered', 'cancelled')),
  customer jsonb not null,
  items jsonb not null,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create or replace function public.is_timed_kids_owner()
returns boolean language sql stable security definer set search_path = ''
as $$ select lower(coalesce(auth.jwt() ->> 'email', '')) = 'rufysurveys@gmail.com' $$;

alter table public.store_products enable row level security;
alter table public.store_orders enable row level security;

create policy "Everyone can view active products" on public.store_products
for select using (is_active = true or public.is_timed_kids_owner());
create policy "Owner can add products" on public.store_products
for insert to authenticated with check (public.is_timed_kids_owner());
create policy "Owner can update products" on public.store_products
for update to authenticated using (public.is_timed_kids_owner()) with check (public.is_timed_kids_owner());
create policy "Owner can delete products" on public.store_products
for delete to authenticated using (public.is_timed_kids_owner());

create policy "Customers can create orders" on public.store_orders
for insert to anon, authenticated with check (status = 'pending');
create policy "Owner can view orders" on public.store_orders
for select to authenticated using (public.is_timed_kids_owner());
create policy "Owner can update orders" on public.store_orders
for update to authenticated using (public.is_timed_kids_owner()) with check (public.is_timed_kids_owner());
create or replace function public.track_store_order(order_reference text)
returns table(reference text, status text, total numeric, created_at timestamptz)
language sql stable security definer set search_path = ''
as $$
  select o.reference, o.status, o.total, o.created_at
  from public.store_orders o
  where upper(o.reference) = upper(order_reference)
  limit 1
$$;
grant execute on function public.track_store_order(text) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 52428800, array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can view product images" on storage.objects
for select using (bucket_id = 'product-images');
create policy "Owner can upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_timed_kids_owner());
create policy "Owner can update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_timed_kids_owner());
create policy "Owner can delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_timed_kids_owner());
